name: Integration

on:
  push:
    branches:
      - renovate/*
      - main
  pull_request:
    branches:
      - main
  workflow_call:
    inputs:
      version:
        description: The version to set in the package.json files
        default: "0.0.0"
        required: false
        type: string
      is_release:
        description: Whether this is a release build
        default: false
        required: false
        type: boolean

jobs:
  codeql:
    name: CodeQL
    uses: ./.github/workflows/codeql.yml
    permissions:
      actions: read
      contents: read
      security-events: write

  format:
    name: Format

    runs-on: ubuntu-latest

    steps:
      - uses: ./.github/actions/setup

      - name: Run Prettier
        run: bunx prettier --check .

  lint:
    name: Lint

    runs-on: ubuntu-latest

    steps:
      - uses: ./.github/actions/setup

      - name: Run ESLint
        run: bunx turbo run lint

  typecheck:
    name: Typecheck

    runs-on: ubuntu-latest

    steps:
      - uses: ./.github/actions/setup

      - name: Run Typecheck
        run: bunx turbo run typecheck

  build:
    name: Build

    runs-on: ubuntu-latest

    steps:
      - uses: ./.github/actions/setup

      - name: Build
        run: bunx turbo run build

      - name: Set Version
        if: inputs.version != ''
        run: bunx turbo run version
        env:
          VERSION: ${{ inputs.version }}

      - name: Upload Build
        uses: actions/upload-artifact@v7
        with:
          name: build
          path: |
            apps/**/dist
            packages/**/dist
            !**/node_modules/**
          retention-days: 1
          include-hidden-files: true

  test:
    name: Unit Test

    runs-on: ubuntu-latest

    steps:
      - uses: ./.github/actions/setup

      - name: Run Unit Tests
        run: bunx turbo run test

      - name: Codecov
        uses: codecov/codecov-action@v5.5.2
        with:
          token: ${{ secrets.CODECOV_TOKEN }}

  local-licenses:
    name: Check Licenses using Build

    needs:
      - build

    runs-on: ubuntu-latest

    steps:
      - uses: ./.github/actions/setup

      - name: Download Build
        uses: actions/download-artifact@v8
        with:
          name: build

      - uses: ./.github/actions/test-cli
        with:
          bin: node ./packages/license-cop/dist/bin.js

  published-licenses:
    name: Check Licenses using the Published Version

    # We don't check this when releasing to make sure that broken released
    # versions don't block fixes
    if: inputs.is_release == false

    needs:
      - build

    runs-on: ubuntu-latest

    steps:
      - uses: ./.github/actions/setup

      - uses: ./.github/actions/test-cli
        with:
          bin: bunx license-cop

  e2e:
    needs:
      - build

    strategy:
      fail-fast: false
      matrix:
        os:
          - name: Ubuntu
            value: ubuntu-latest
          - name: MacOS
            value: macos-latest
          - name: Windows
            value: windows-latest
        node:
          - 20
          - 22
          - 24

    name: E2E Test License-Cop (Node ${{ matrix.node }} on ${{ matrix.os.name }})

    runs-on: ${{ matrix.os.value }}

    steps:
      - uses: ./.github/actions/setup
        with:
          node-version: ${{ matrix.node }}

      - name: Install Package Managers
        run: corepack enable

      - name: Download Build
        uses: actions/download-artifact@v8
        with:
          name: build

      - name: Run E2E Tests
        run: bunx turbo run e2e --filter=license-cop-e2e

  e2e-website:
    name: E2E Test Website

    needs:
      - build

    runs-on: ubuntu-latest

    steps:
      - uses: ./.github/actions/setup

      - name: Download Build
        uses: actions/download-artifact@v8
        with:
          name: build

      - name: Install Playwright Browsers
        run: bunx playwright install --with-deps chromium firefox

      - name: Run E2E Tests
        run: bunx turbo run e2e --filter=website-e2e
